<a href="https://colab.research.google.com/github/zlwym/Mann_Zoe_LabTask/blob/main/labtask04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv("youtube_videos.csv")

In [ ]:
df.head()

,video_id,title,category,channel_tier,upload_day,upload_hour,duration_seconds,views,likes,comments,shares,watch_time_minutes,avg_view_duration_seconds,click_through_rate,channel_age_years,subscribers,tags_count,hashtags
0,vid_0000,I tried EVERY transformers tool — the WINNER s...,Music,Mid,Sunday,0,721,228102,9979,2810,1193,1091087,287,0.0100,1.3,441016,18.0,"[""ai"", ""tutorial"", ""trending""]"
1,vid_0001,What nobody tells you about AI image tools,Gaming,Small,Saturday,21,1894,25078,962,283,183,423818,1014,0.0230,0.8,25339,17.0,"[""tutorial""]"
2,vid_0002,What nobody tells you about machine learning p...,Gaming,Large,Monday,18,1413,1323949,6619,25177,16119,12952634,587,0.1022,4.8,2398429,NaN,"[""explained""]"
3,vid_0003,Is Claude worth it in 2025?,Gaming,Mid,Thursday,14,1335,187752,4936,2051,1797,2018334,645,0.0413,3.9,498144,13.0,"[""gaming"", ""trending"", ""explained"", ""tech""]"
4,vid_0004,URGENT: voice cloning AI is about to CHANGE FO...,Music,Small,Monday,4,3158,12583,777,98,30,262565,1252,0.0100,1.3,30039,10.0,"[""explained"", ""shorts""]"

In [ ]:
df["subscribers"]

0       441016
1        25339
2      2398429
3       498144
4        30039
        ...
205      13428
206      10005
207     483919
208      11937
209     553531
Name: subscribers, Length: 210, dtype: int64

In [ ]:
scaler = MinMaxScaler()

In [ ]:
df["subscribers_minmax"] = scaler.fit_transform(df[["subscribers"]])

In [ ]:
df["subscribers"].describe()

count    2.100000e+02
mean     1.005263e+06
std      2.063624e+06
min      5.624000e+03
25%      2.544875e+04
50%      1.359100e+05
75%      4.862028e+05
max      7.763623e+06
Name: subscribers, dtype: float64

In [ ]:
standard_scaler = StandardScaler()

In [ ]:
df["view_zscore"] = standard_scaler.fit_transform(df[["views"]])

In [ ]:
df[["views", "view_zscore"]]